export const CHARACTER_META = {
  characters: [
    {
      id: "penny",
      birthday: "November 12",
      zodiac: "Scorpio",
      mbti: "ESFP",
      bloodType: "O",
      recommendations: {
        drink: "Apple Juice",
        snack: "Inari-Zushi",
        entree: "Katsudon",
        dessert: "Ice Cream Float",
      },
    },
    {
      id: "sandy",
      birthday: "July 7",
      zodiac: "Cancer",
      mbti: "ISFP",
      bloodType: "A",
      recommendations: {
        drink: "Latte",
        snack: "Inari-Zushi",
        entree: "Egg Sandwich",
        dessert: "Crepe",
      },
    },
    {
      id: "mandy",
      birthday: "August 15",
      zodiac: "Leo",
      mbti: "INFJ",
      bloodType: "AB",
      recommendations: {
        drink: "Matcha",
        snack: "Edamame",
        entree: "Eggplant Curry",
        dessert: "Fruit Tart",
      },
    },
    {
      id: "cybill",
      birthday: "April 9",
      zodiac: "Aries",
      mbti: "ESTP",
      bloodType: "B",
      recommendations: {
        drink: "Cola",
        snack: "Gyoza",
        entree: "Carbonara",
        dessert: "Ice Cream Float",
      },
    },
    {
      id: "yuki",
      birthday: "January 29",
      zodiac: "Aquarius",
      mbti: "INFP",
      bloodType: "A",
      recommendations: {
        drink: "Melon Soda",
        snack: "Onigiri",
        entree: "Spaghetti",
        dessert: "Cheesecake",
      },
    },
    {
      id: "kara",
      birthday: "October 3",
      zodiac: "Libra",
      mbti: "ENFJ",
      bloodType: "O",
      recommendations: {
        drink: "Coffee",
        snack: "Gyoza",
        entree: "Katsudon",
        dessert: "Cake Slice",
      },
    },
    {
      id: "zuri",
      birthday: "May 2",
      zodiac: "Taurus",
      mbti: "ENTP",
      bloodType: "B",
      recommendations: {
        drink: "Cola",
        snack: "French Fries",
        entree: "Club Sandwich",
        dessert: "Ice Cream Float",
      },
    },
    {
      id: "akane",
      birthday: "September 18",
      zodiac: "Virgo",
      mbti: "ISFJ",
      bloodType: "A",
      recommendations: {
        drink: "Matcha",
        snack: "Dango",
        entree: "Egg Sandwich",
        dessert: "Crepe",
      },
    },
    {
      id: "maris",
      birthday: "March 14",
      zodiac: "Pisces",
      mbti: "INTP",
      bloodType: "AB",
      recommendations: {
        drink: "Apple Juice",
        snack: "Edamame",
        entree: "Spaghetti",
        dessert: "Berry Parfait",
      },
    },
    {
      id: "cora",
      birthday: "August 28",
      zodiac: "Virgo",
      mbti: "ESFJ",
      bloodType: "O",
      recommendations: {
        drink: "Cola",
        snack: "Onigiri",
        entree: "Club Sandwich",
        dessert: "Cake Slice",
      },
    },
    {
      id: "juni",
      birthday: "June 6",
      zodiac: "Gemini",
      mbti: "ENFP",
      bloodType: "B",
      recommendations: {
        drink: "Melon Soda",
        snack: "Edamame",
        entree: "Eggplant Curry",
        dessert: "Berry Parfait",
      },
    },
    {
      id: "nika",
      birthday: "December 8",
      zodiac: "Sagittarius",
      mbti: "ISFP",
      bloodType: "O",
      recommendations: {
        drink: "Latte",
        snack: "French Fries",
        entree: "Katsudon",
        dessert: "Fruit Tart",
      },
    },
    {
      id: "naomi",
      birthday: "February 22",
      zodiac: "Pisces",
      mbti: "ISTP",
      bloodType: "B",
      recommendations: {
        drink: "Apple Juice",
        snack: "Edamame",
        entree: "Carbonara",
        dessert: "Cheesecake",
      },
    },

    {
      id: "elise",
      birthday: "January 5",
      zodiac: "Capricorn",
      mbti: "INTJ",
      bloodType: "AB",
      recommendations: {
        drink: "Coffee",
        snack: "Inari-Zushi",
        entree: "Spaghetti",
        dessert: "Fruit Tart",
      },
    },
    {
      id: "noa",
      birthday: "April 18",
      zodiac: "Aries",
      mbti: "INFP",
      bloodType: "A",
      recommendations: {
        drink: "Matcha",
        snack: "Dango",
        entree: "Eggplant Curry",
        dessert: "Berry Parfait",
      },
    },
  ],
};
